version: '3'

services:
  exporter:
    build: .
    ports:
      - "9179:9179"
    volumes:
      - /var/run/libvirt/libvirt-sock:/var/run/libvirt/libvirt-sock
    restart: unless-stopped
    privileged: true

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./examples/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - exporter

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
